### ISSUE TITLE
Implement API method for cancelling envelope

### ISSUE THREAD

**Issue by adamstirtan** [fernsoftware/RSignSDK#3]
The SDK should support cancelling envelopes. This enables someone using Abacus to send an envelope (in error) and then cancel it so if the end-user clicks the link to sign, it will tell them the signature request is no longer valid.

https://webapi.rsign.com/Help/Api/GET-api-V1-Manage-CancelEnvelopeTrans-envelopeID

It's a fairly easy one to implement in code. It should be exposed via the public IRSignApi interface so Abacus can use it.

![image](https://user-images.githubusercontent.com/9989813/59356726-763c8800-8cf7-11e9-9f83-be9e9624f312.png)

**Comment by jamesfernsoftware** [comment]
#
